// Package memory provides project-scoped hybrid semantic+keyword (RAG) memory
// for vornik. Text artifacts from completed tasks are chunked, stored, and
// optionally embedded for vector similarity search.
package memory

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/rs/zerolog"

	"vornik.io/vornik/internal/secrets"
)

const stateCollectInterval = 30 * time.Second

// Manager is the top-level facade for the memory subsystem.
// It owns the Indexer, Searcher, and the background embed worker.
type Manager struct {
	// Indexer is the public interface for ingesting content into memory.
	Indexer *Indexer

	// Searcher is the public interface for querying project memory.
	Searcher *Searcher

	// Embedder is exposed so the KG extraction pipeline (in
	// internal/memory/graph) can re-use it when populating
	// canonical_name vectors on new knowledge_entities rows.
	// Nil-safe — when EmbeddingEndpoint is empty the embedder
	// returns (nil, nil) on every call and the resolver falls
	// back to its name-substring shortlist path.
	Embedder *Embedder

	// ResponseCache is the Phase E full-response cache shared by
	// Titler / Classifier / KG Extractor. Nil when disabled. Exposed
	// so the service container can pass the same instance into all
	// three constructors and so the UI can pull CacheStats.
	ResponseCache ResponseCache

	worker *Worker
	repo   *Repository
	logger zerolog.Logger
}

// New creates a Manager with all sub-components wired together.
// Returns an error only for configuration issues that would make the system
// permanently broken (e.g. nil db). A disabled memory system returns a valid
// Manager with no-op components.
func New(cfg Config, db *sql.DB, logger zerolog.Logger) (*Manager, error) {
	if db == nil {
		return nil, fmt.Errorf("memory: db must not be nil")
	}

	// Apply defaults for zero-valued fields.
	defaults := DefaultConfig()
	if cfg.EmbeddingDimension <= 0 {
		cfg.EmbeddingDimension = defaults.EmbeddingDimension
	}
	if cfg.ChunkTokens <= 0 {
		cfg.ChunkTokens = defaults.ChunkTokens
	}
	if cfg.ChunkOverlap < 0 {
		cfg.ChunkOverlap = defaults.ChunkOverlap
	}
	if cfg.WorkerConcurrency <= 0 {
		cfg.WorkerConcurrency = defaults.WorkerConcurrency
	}

	repo := NewRepository(db)
	embedder := NewEmbedder(cfg)
	// Phase D — embedding cache. When the daemon has pgvector +
	// the embedding_cache table (migration 41), wire a postgres-
	// backed cache so identical (content, model) pairs skip the
	// upstream API call. Operators who run without postgres or
	// who haven't applied migration 41 yet get a nil cache here
	// (the Embedder degrades to the slice-0 always-upstream
	// behaviour).
	if cfg.EmbeddingCacheEnabled {
		embedder.Cache = NewEmbeddingCache(db)
	}

	// Phase E — response cache. Same shape as the embedding cache:
	// opt-in via cfg.ResponseCacheEnabled, postgres-backed, nil
	// when disabled so the callers (Titler / Classifier / KG
	// Extractor) degrade to always-upstream behaviour. When the
	// service container wired cfg.PricingFunc, the cache stats
	// will surface a "$ saved" headline; otherwise hits-only.
	var responseCache ResponseCache
	if cfg.ResponseCacheEnabled {
		if cfg.PricingFunc != nil {
			responseCache = NewResponseCacheWithPricing(db, cfg.PricingFunc)
		} else {
			responseCache = NewResponseCache(db)
		}
	}

	indexer := NewIndexer(cfg, repo, embedder,
		logger.With().Str("component", "memory.indexer").Logger())
	searcher := NewSearcher(cfg, repo, embedder)
	worker := NewWorker(cfg, repo, embedder,
		logger.With().Str("component", "memory.worker").Logger())

	return &Manager{
		Indexer:       indexer,
		Searcher:      searcher,
		Embedder:      embedder,
		ResponseCache: responseCache,
		worker:        worker,
		repo:          repo,
		logger:        logger.With().Str("component", "memory").Logger(),
	}, nil
}

// Repository exposes the underlying chunk repo. Used by the
// Pipeline (Phase 2) to look up chunk existence by hash for the
// dedup gate without re-instantiating a repo.
func (m *Manager) Repository() *Repository {
	if m == nil {
		return nil
	}
	return m.repo
}

// SetMetrics wires a Metrics instance into all sub-components.
func (m *Manager) SetMetrics(metrics *Metrics) {
	m.Indexer.setMetrics(metrics)
	m.worker.setMetrics(metrics)
	m.Searcher.setMetrics(metrics)
}

// SetSecrets wires the secret-leak detector into the indexer so
// content is scanned before chunking.
func (m *Manager) SetSecrets(d secrets.Detector, actions map[string]secrets.Action) {
	if m == nil || m.Indexer == nil {
		return
	}
	m.Indexer.SetSecrets(d, actions)
}

// SetTitler wires a Titler into the embed worker so each chunk gets
// a display-friendly topic label generated by an LLM after embedding
// succeeds. Nil-safe: leaving titler unset keeps the legacy behaviour
// (content_title stays NULL and the viz falls back to the markdown
// heading / filename).
func (m *Manager) SetTitler(t *Titler) {
	if m == nil || m.worker == nil {
		return
	}
	m.worker.SetTitler(t)
}

// Start launches the background embed worker. Must be called after New().
// The worker stops when ctx is cancelled or Stop() is called.
func (m *Manager) Start(ctx context.Context) {
	m.logger.Info().Msg("memory manager starting")
	m.worker.Start(ctx)
	if m.worker.metrics != nil {
		go m.collectStateGauges(ctx, m.worker.metrics)
	}
}

// collectStateGauges periodically refreshes ChunksTotal and QueueDepth gauges.
func (m *Manager) collectStateGauges(ctx context.Context, metrics *Metrics) {
	ticker := time.NewTicker(stateCollectInterval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			states, err := m.repo.QueryState(ctx)
			if err != nil {
				m.logger.Warn().Err(err).Msg("memory: failed to collect state gauges")
				continue
			}
			for _, s := range states {
				metrics.ChunksTotal.WithLabelValues(s.ProjectID).Set(float64(s.ChunksTotal))
				metrics.QueueDepth.WithLabelValues(s.ProjectID).Set(float64(s.QueueDepth))
			}
		}
	}
}

// Stop shuts down the background worker gracefully.
// Stats returns per-project chunk / embedding / queue-depth counts.
// Delegates to the repo so consumers don't need to hold a direct
// Repository reference.
func (m *Manager) Stats(ctx context.Context) ([]ProjectMemoryStats, error) {
	if m == nil || m.repo == nil {
		return nil, nil
	}
	return m.repo.Stats(ctx)
}

func (m *Manager) Stop() {
	m.logger.Info().Msg("memory manager stopping")
	m.worker.Stop()
}
