package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"vornik.io/vornik/internal/agenttools"
)

// toolRegistryFile is the container's tool registries, generated from
// internal/agenttools.Tools. The entrypoint sources it before its first use of
// any registry variable; the Containerfile copies it beside the entrypoint.
// Design: https://docs.vornik.io §3.
const toolRegistryFile = "images/vornik-agent/tool_registry.generated.sh"

// renderToolRegistry emits the shell file. Deterministic: Tools is sorted,
// every JSON value is re-marshalled through Go's encoder (sorted keys), and
// the three name arrays are single-quoted JSON so contractreg's existing
// parsers read them unchanged. The definitions carry apostrophes, so the
// registry array goes through a quoted heredoc rather than a single-quoted
// string — `read -r -d ”` rather than `$(cat <<EOF)`, because a heredoc inside
// a command substitution is the bash 3.2 parse trap scripts/check-bash32-heredoc.sh
// exists for.
func renderToolRegistry() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# GENERATED by `go run ./cmd/docs-gen tools` from internal/agenttools/agenttools.go — do not edit.\n")
	b.WriteString("# `make docs-gen-check` fails when this file is stale. Design of record:\n")
	b.WriteString("# https://docs.vornik.io\n")
	b.WriteString("#\n")
	b.WriteString("# BUILTIN_TOOL_NAMES_JSON   — declared tools tool_definitions() may offer (Advertise != Never);\n")
	b.WriteString("#                             the \"declared\" set the fail-closed advertisement filter consults.\n")
	b.WriteString("# UNGATED_TOOL_NAMES_JSON   — exempt from BOTH gates, each with a reason in agenttools.Tools.\n")
	b.WriteString("# UNGATED_TOOL_PREFIXES_JSON — name prefixes gated somewhere other than the container.\n")
	b.WriteString("# HELPER_TOOL_NAMES_JSON    — declared tools whose dispatch is `vornik-agent-helper exec-tool`;\n")
	b.WriteString("#                             exec_tool delegates exactly these, AFTER the gate.\n")
	b.WriteString("# ADVERTISE_TOKENS_JSON     — the closed set tool_advertised_now() must switch on.\n")
	b.WriteString("# TOOL_REGISTRY_JSON        — every declared tool: name, advertise token, OpenAI definition.\n")
	b.WriteString("# shellcheck disable=SC2034\n\n")

	names, err := json.Marshal(agenttools.Offerable())
	if err != nil {
		return nil, err
	}
	exempt, err := json.Marshal(agenttools.ExemptNames())
	if err != nil {
		return nil, err
	}
	var prefixes []string
	for _, p := range agenttools.UngatedPrefixes {
		prefixes = append(prefixes, p.Prefix)
	}
	prefixJSON, err := json.Marshal(prefixes)
	if err != nil {
		return nil, err
	}
	tokens, err := json.Marshal(agenttools.AdvertiseTokens())
	if err != nil {
		return nil, err
	}
	helper, err := json.Marshal(agenttools.HelperNames())
	if err != nil {
		return nil, err
	}
	fmt.Fprintf(&b, "BUILTIN_TOOL_NAMES_JSON='%s'\n", names)
	fmt.Fprintf(&b, "UNGATED_TOOL_NAMES_JSON='%s'\n", exempt)
	fmt.Fprintf(&b, "UNGATED_TOOL_PREFIXES_JSON='%s'\n", prefixJSON)
	fmt.Fprintf(&b, "HELPER_TOOL_NAMES_JSON='%s'\n", helper)
	fmt.Fprintf(&b, "ADVERTISE_TOKENS_JSON='%s'\n", tokens)

	type entry struct {
		Name       string          `json:"name"`
		Advertise  string          `json:"advertise"`
		Definition json.RawMessage `json:"definition"`
	}
	entries := make([]entry, 0, len(agenttools.Tools))
	for _, t := range agenttools.Tools {
		var def any
		if err := json.Unmarshal(t.Schema, &def); err != nil {
			return nil, fmt.Errorf("%s: schema: %w", t.Name, err)
		}
		canon, err := json.Marshal(def)
		if err != nil {
			return nil, err
		}
		entries = append(entries, entry{Name: t.Name, Advertise: t.Advertise.Token(), Definition: canon})
	}
	registry, err := json.Marshal(entries)
	if err != nil {
		return nil, err
	}
	if bytes.Contains(registry, []byte("\nTOOL_REGISTRY_EOF\n")) {
		return nil, fmt.Errorf("a definition contains the heredoc terminator")
	}
	b.WriteString("read -r -d '' TOOL_REGISTRY_JSON <<'TOOL_REGISTRY_EOF' || true\n")
	b.Write(registry)
	b.WriteString("\nTOOL_REGISTRY_EOF\n")
	return b.Bytes(), nil
}

// writeToolRegistry renders and writes the file under root.
func writeToolRegistry(root string) {
	out, err := renderToolRegistry()
	if err != nil {
		fatal(err)
	}
	path := filepath.Join(root, toolRegistryFile)
	if err := os.WriteFile(path, out, 0o644); err != nil {
		fatal(err)
	}
}
