package api

import (
	"context"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"vornik.io/vornik/internal/apikey"
	"vornik.io/vornik/internal/persistence"
)

// gitProjectIDRe matches the allowed project-id charset: ASCII alphanumerics,
// underscores, and hyphens. Real project IDs are generated by
// persistence.GenerateID("proj") and contain only [A-Za-z0-9_].  The hyphen
// is included in the allowlist as a safe superset (no real ID uses it today,
// but the charset is forward-compatible and still excludes all path-traversal
// and shell-meta characters).
var gitProjectIDRe = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

// sanitizeGitProjectID validates and returns the raw projectID path segment.
// It rejects:
//   - empty strings
//   - the dot-dot sequence ".." (path traversal)
//   - any path separators ("/" or "\")
//   - null bytes ("\x00")
//   - anything not matching ^[A-Za-z0-9_-]+$ (excludes shell-meta like $, (, ))
//
// On success it returns the unchanged raw string and a nil error.
// Callers should respond with 404 on error to avoid leaking information.
//
//nolint:unparam // return value used by the git-http-backend handler (Task 2.x); noop until wired.
func sanitizeGitProjectID(raw string) (string, error) {
	if raw == "" {
		return "", fmt.Errorf("sanitizeGitProjectID: empty project ID")
	}
	if strings.Contains(raw, "..") || strings.ContainsAny(raw, "/\\\x00") {
		return "", fmt.Errorf("sanitizeGitProjectID: unsafe characters in project ID %q", raw)
	}
	if !gitProjectIDRe.MatchString(raw) {
		return "", fmt.Errorf("sanitizeGitProjectID: project ID %q contains disallowed characters", raw)
	}
	return raw, nil
}

// gitService identifies which git smart-HTTP service a request targets.
// gitServiceUpload is the read path (clone/fetch); gitServiceReceive is the
// write path (push), gated by the allow_push capability (Task 2.4).
type gitService int

const (
	// gitServiceUpload is git-upload-pack: read (clone/fetch) access.
	gitServiceUpload gitService = iota
	// gitServiceReceive is git-receive-pack: write (push) access.
	gitServiceReceive gitService = iota
)

// gitKeyCtxKey is the context key for the resolved *persistence.APIKey.
// nil when authEnabled == false (anonymous access).
type gitKeyCtxKey struct{}

// gitRemoteUserCtxKey is the context key for the sanitized REMOTE_USER
// string that git-http-backend expects.
type gitRemoteUserCtxKey struct{}

// gitServiceCtxKey carries the resolved gitService (upload vs receive) to the
// downstream GitHTTPBackend handler so it can pick the right workspace-lock
// mode (RLock for read, exclusive Lock for push), run the push gate, and
// stamp the correct audit Action without re-parsing the path.
type gitServiceCtxKey struct{}

// gitHTTPAuth returns a per-service middleware that authenticates git
// smart-HTTP requests against the project-scoped API-key system.
//
// For the read path (gitServiceUpload):
//   - Missing or unrecognisable credentials → 401 + WWW-Authenticate.
//   - Valid key that does not belong to the path's project → 404 (avoids
//     a project-existence oracle: the caller can't distinguish "wrong
//     project" from "no such project").
//   - Valid key bound to the path's project → 200, key + REMOTE_USER
//     stamped on context.
//
// When authEnabled == false the lookup is skipped: the caller is treated
// as full-access, a nil key is stamped on context, and REMOTE_USER is
// set to "anonymous".
//
// adminCheck receives the raw (unhashed) key and reports whether it is
// admin-class. Admin keys are not restricted to a single project so the
// project-match gate is skipped for them.
func gitHTTPAuth(
	repo persistence.APIKeyRepository,
	adminCheck func(string) bool,
	authEnabled bool,
) func(service gitService, next http.Handler) http.Handler {
	return func(service gitService, next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// auth_enabled=false → skip key lookup, treat as full-access.
			// auth-disabled == full access, so push capability is implied;
			// no separate gitServiceReceive gate here.
			if !authEnabled {
				ctx := context.WithValue(r.Context(), gitKeyCtxKey{}, (*persistence.APIKey)(nil))
				ctx = context.WithValue(ctx, gitRemoteUserCtxKey{}, "anonymous")
				ctx = context.WithValue(ctx, gitServiceCtxKey{}, service)
				next.ServeHTTP(w, r.WithContext(ctx))
				return
			}

			// Extract the raw credential — extractAPIKey already handles
			// HTTP Basic (password field), Authorization: Bearer, and
			// X-API-Key in order.
			//
			// IMPORTANT (Task 1.4 carryover fix): the push-capability gate
			// MUST run AFTER credential validation, so an unauthenticated
			// push attempt returns 401 + WWW-Authenticate (NOT 403). 403 is
			// reserved for an authenticated-but-unprivileged key.
			rawKey := extractAPIKey(r)
			if rawKey == "" {
				gitUnauthorized(w)
				return
			}

			// Hash and look up.
			keyHash := apikey.Hash(rawKey)
			apiKey, err := repo.LookupActiveByHash(r.Context(), keyHash)
			if err != nil || apiKey == nil {
				// ErrAPIKeyNotFound or any other lookup failure → 401.
				gitUnauthorized(w)
				return
			}

			isAdmin := adminCheck(rawKey)

			// Project-scope check: admin keys bypass, everyone else must
			// match the project in the URL path. Return 404 on mismatch
			// to avoid leaking whether the project exists.
			projectID := r.PathValue("projectID")
			if !isAdmin && apiKey.ProjectID != projectID {
				http.NotFound(w, r)
				return
			}

			// Push-capability gate (Task 2.4). Only the receive (push)
			// service is gated; reads pass on a valid project-scoped key.
			// Allowed when the key is admin-class OR carries allow_push.
			// A read-only key (AllowPush=false, non-admin) → 403 via the
			// JSON error envelope (Task 1.4 carryover: was bare http.Error).
			if service == gitServiceReceive && !isAdmin && !apiKey.AllowPush {
				respondError(w, http.StatusForbidden, "FORBIDDEN",
					"git push not permitted: this key lacks the allow_push capability")
				return
			}

			// Stamp the resolved key, the sanitized REMOTE_USER, and the
			// service onto the context so the downstream git-http-backend
			// handler can use them without re-authenticating.
			remoteUser := sanitizeRemoteUser(apiKey.Name)
			ctx := context.WithValue(r.Context(), gitKeyCtxKey{}, apiKey)
			ctx = context.WithValue(ctx, gitRemoteUserCtxKey{}, remoteUser)
			ctx = context.WithValue(ctx, gitServiceCtxKey{}, service)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

// gitUnauthorized writes a 401 with the WWW-Authenticate challenge the
// git CLI expects to trigger its credential-helper prompt.
func gitUnauthorized(w http.ResponseWriter) {
	w.Header().Set("WWW-Authenticate", `Basic realm="vornik-git"`)
	respondError(w, http.StatusUnauthorized, "UNAUTHORIZED", "git authentication required")
}

// sanitizeRemoteUser strips characters that are unsafe to pass through
// to git-http-backend via the REMOTE_USER environment variable: control
// characters, newlines, and shell-meta characters. Returns "key" when
// the result would be empty.
func sanitizeRemoteUser(name string) string {
	var b strings.Builder
	for _, r := range name {
		if r < 0x20 || r == 0x7f || strings.ContainsRune("\r\n`$\"';\\", r) {
			continue
		}
		b.WriteRune(r)
	}
	if b.Len() == 0 {
		return "key"
	}
	return b.String()
}
