// Package aidisclosure owns vornik's EU AI Act Article 50(1) conformity
// policy: whether a given turn on a given channel must tell the human that
// they are talking to an AI system, and what that notice says.
//
// The package deliberately knows nothing about transport. It decides; the
// dispatcher's ChannelReceiver delivers. That split is what makes the policy
// unit-testable without a channel stub, and it is why a new channel cannot
// forget to disclose — the decision is taken at one chokepoint rather than in
// five channel implementations.
//
// Article 50(1) binds the PROVIDER of a system intended to interact directly
// with natural persons, from the moment the system is placed on the market —
// not from the moment a paying tenant arrives. It applies from 2 August 2026
// and was NOT deferred by the Digital Omnibus on AI, which moved only the
// high-risk provisions. Art 99 penalties for breach: up to EUR 15M or 3% of
// worldwide annual turnover.
//
// Design: https://docs.vornik.io
// Audit:  docs/audits/2026-07-28-eu-ai-act-readiness.md
package aidisclosure

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
)

// DefaultURL is where the public AI-transparency statement lives. The
// statement MUST exist before the disclosure ships, or every notice links to
// a 404 (design §8).
const DefaultURL = "https://docs.vornik.io/ai-transparency"

// DefaultText is the compiled-in disclosure. Plain language rather than a
// citation: the obligation is to inform the human, not to cite the article at
// them. The %s is the transparency-statement URL.
//
// Kept free of markup so it survives being read as plain text on every
// channel — a disclosure that renders only visually (an image, a colour, an
// emoji) fails both the accessibility and the "clear and distinguishable"
// limbs of Art 50(5) for a non-sighted reader.
const DefaultText = "You are interacting with an AI system. Replies in this " +
	"conversation are generated by an AI model, not a human. More: %s"

// DefaultPublicationText is the disclosure for surfaces where this system
// AUTHORS an artifact rather than replying in a conversation — a forge review
// comment, a post on a social platform. The %s is the transparency URL.
//
// DefaultText cannot be reused there: "Replies in this conversation" is false
// of an originated artifact, and a disclosure that misdescribes what the reader
// is looking at is weaker than a shorter accurate one. Same plain-text
// discipline as DefaultText — it has to survive being read as plain text, and
// on these surfaces it also has to survive being quoted into another thread.
//
// Design: https://docs.vornik.io
const DefaultPublicationText = "This was written by an AI agent, not a human. More: %s"

// Notice is the rendered disclosure plus its evidentiary fingerprint.
type Notice struct {
	// Text is the full rendered notice, URL included.
	Text string

	// Hash is the SHA-256 of Text, lower-case hex over its UTF-8 bytes.
	//
	// This is an evidentiary artifact, not a cache key. It answers "which
	// exact wording was this session served?" when an enforcement request
	// asks. Do not swap it for a faster non-cryptographic hash: it runs
	// once per session, and the cryptographic property is the entire point.
	Hash string
}

// Config is the operator-tunable surface.
//
// There is deliberately NO Enabled field. Art 50(1) is a legal obligation
// with a EUR 15M / 3% ceiling; a config key whose only function is to create
// silent non-conformity is a liability, not a feature. An operator who truly
// must suppress the disclosure can patch the binary — a deliberate, visible
// act rather than a YAML boolean nobody reviews.
type Config struct {
	// Text overrides DefaultText. Must contain a %s for the URL, or the URL
	// is appended. Empty means "use the compiled default".
	Text string `yaml:"text" json:"text"`

	// PublicationText overrides DefaultPublicationText for surfaces this
	// system authors rather than converses on. Must contain a %s for the URL,
	// or the URL is appended. Empty means "use the compiled default".
	PublicationText string `yaml:"publication_text" json:"publication_text"`

	// URL overrides DefaultURL. Empty means "use the compiled default".
	URL string `yaml:"url" json:"url"`
}

// ErrBlankDisclosureText rejects a whitespace-only text override. Without
// this, "customise the wording" would be a back door to the off-switch the
// design refuses to provide.
var ErrBlankDisclosureText = errors.New(
	"ai_disclosure.text: must not be blank — the AI Act Art 50(1) disclosure " +
		"cannot be disabled by blanking its text")

// Validate reports whether the config is usable. A zero Config is valid and
// means "use the compiled defaults".
func (c Config) Validate() error {
	if c.Text != "" && strings.TrimSpace(c.Text) == "" {
		return ErrBlankDisclosureText
	}
	if c.PublicationText != "" && strings.TrimSpace(c.PublicationText) == "" {
		return ErrBlankDisclosureText
	}
	return nil
}

// Store persists which (channel, session) pairs have already been disclosed
// to. Backed by channel_disclosure_log; it is simultaneously the per-session
// state and the Art 99 evidence trail.
type Store interface {
	WasServed(ctx context.Context, channel, sessionID string) (bool, error)
	MarkServed(ctx context.Context, channel, sessionID, textHash string) error
}

// Service decides whether a turn must carry the disclosure.
type Service struct {
	notice Notice
	// publication is the notice for authored artifacts (§3 of the publication
	// -surface design). Rendered once at construction like notice, so a
	// publication surface pays no per-post cost and cannot render a variant.
	publication Notice
	store       Store
}

// New builds a Service. A nil store is allowed and means "no per-session
// memory": every turn serves. That degrades toward disclosure, never away
// from it, which keeps the zero-wiring case conforming.
func New(cfg Config, store Store) *Service {
	return &Service{
		notice:      render(cfg.Text, DefaultText, cfg.URL),
		publication: render(cfg.PublicationText, DefaultPublicationText, cfg.URL),
		store:       store,
	}
}

// render resolves one notice: the operator override when set, else the compiled
// default, with the URL interpolated (or appended when the override carries no
// placeholder) and the evidentiary hash taken over the final text.
func render(override, compiledDefault, cfgURL string) Notice {
	text, url := override, cfgURL
	if strings.TrimSpace(text) == "" {
		text = compiledDefault
	}
	if strings.TrimSpace(url) == "" {
		url = DefaultURL
	}

	if strings.Contains(text, "%s") {
		text = fmt.Sprintf(text, url)
	} else if !strings.Contains(text, url) {
		// A custom text with no placeholder still has to reach the
		// statement — Art 50(5) wants the information accessible, and a
		// notice with no route to the detail is a weaker one.
		text = text + " " + url
	}

	sum := sha256.Sum256([]byte(text))
	return Notice{Text: text, Hash: hex.EncodeToString(sum[:])}
}

// Notice returns the rendered disclosure for this service.
func (s *Service) Notice() Notice { return s.notice }

// PublicationNotice returns the disclosure for surfaces that AUTHOR an artifact
// — a forge review, a social post — rather than reply in a conversation.
//
// There is no Ensure/Record pair for these: every authored artifact carries the
// notice, unconditionally. Cadence would be meaningless (there is no session)
// and a per-artifact suppression rule is exactly the off-switch §5 refuses. The
// published artifact carries the notice verbatim and is therefore its own Art 99
// evidence, which is why these surfaces write no channel_disclosure_log row.
func (s *Service) PublicationNotice() Notice { return s.publication }

// Ensure reports whether this turn must carry the disclosure.
//
// Per-message channels always serve and never touch the store. Per-session
// channels consult it — and on a READ error serve anyway, returning the error
// for logging: a duplicate notice is a UX blemish, a skipped one is
// non-conformity, so the failure direction is toward disclosure (design §4).
func (s *Service) Ensure(ctx context.Context, channel, sessionID string) (Notice, bool, error) {
	if CadenceFor(channel) == CadencePerMessage {
		return s.notice, true, nil
	}
	if s.store == nil {
		return s.notice, true, nil
	}

	served, err := s.store.WasServed(ctx, channel, sessionID)
	if err != nil {
		return s.notice, true, fmt.Errorf("aidisclosure: read served state: %w", err)
	}
	return s.notice, !served, nil
}

// Record marks a per-session notice as served. A no-op for per-message
// channels, which keep no per-session state, and for a nil store.
//
// Callers MUST NOT fail the turn on a Record error: the human has already
// been disclosed to, so the obligation is met and only the evidence trail
// degraded. Log it, alert on it (design §4.1), and carry on.
func (s *Service) Record(ctx context.Context, channel, sessionID string, n Notice) error {
	if CadenceFor(channel) == CadencePerMessage || s.store == nil {
		return nil
	}
	return s.store.MarkServed(ctx, channel, sessionID, n.Hash)
}
