#!/usr/bin/env bash
# Generate the operator shell-env fragment.
#
# WHY THIS EXISTS (incident T-1089, 2026-07-28): `vornikctl` runs the SAME
# config load + validation the daemon does, but it resolves paths and secrets
# from the INVOKING SHELL — not from the systemd unit. So a command like
# `vornikctl backup` fails in a plain shell with an error about an unrelated
# capability secret (`web.submit_secret`) purely because the shell lacks the
# daemon's environment. Same trap as `vornikctl doctor --offline`, which "sees
# your shell, not the daemon".
#
# This writes a fragment the operator's shell can source so CLI and daemon
# agree. It contains ONLY non-secret paths plus a loop that sources the
# already-protected secret files. Secret VALUES are never written here — the
# fragment is world-readable, the secret files are 0600.
#
# Usage: gen-shell-env.sh <config-dir> <data-dir> <out-file>
set -euo pipefail

CONFIG_DIR="${1:?config dir required}"
DATA_DIR="${2:?data dir required}"
OUT="${3:?output path required}"

# The running unit is the authority when it exists. A dev box may legitimately
# deviate from the build-time defaults (this one keeps DATA_DIR on the historical
# ~/.local/share/swarmd path), and baking the Makefile default into the fragment
# would hand the CLI a data dir the daemon never uses. Parse the unit's
# Environment= list; fall back to the passed-in defaults when there is no unit.
unit_env() {
  local key="$1" out
  command -v systemctl >/dev/null 2>&1 || return 1
  out="$(systemctl --user show vornik.service --property=Environment --value 2>/dev/null || true)"
  [ -n "$out" ] || return 1
  # Environment= is a space-separated K=V list. Emit the first match's value.
  tr ' ' '\n' <<<"$out" | sed -n "s/^${key}=//p" | head -n1
}

resolved_config="$(unit_env VORNIK_CONFIG || true)"
resolved_data="$(unit_env VORNIK_DATA_DIR || true)"
resolved_configs_dir="$(unit_env VORNIK_CONFIGS_DIR || true)"

[ -n "$resolved_config" ] || resolved_config="${CONFIG_DIR}/config.yaml"
[ -n "$resolved_data" ] || resolved_data="$DATA_DIR"
[ -n "$resolved_configs_dir" ] || resolved_configs_dir="${CONFIG_DIR}/configs"

secrets_dir="${CONFIG_DIR}/secrets"

# The database THIS deployment writes, read out of its own config so the value is
# never hardcoded in shipped source. Used only to DENY it as a benchmark target.
resolved_db="$(sed -n 's/^[[:space:]]*name:[[:space:]]*\(.*\)$/\1/p' "$resolved_config" 2>/dev/null | head -1 | tr -d '"'"'"' ')"

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# shellcheck shell=sh
# Vornik operator shell environment — GENERATED by scripts/gen-shell-env.sh.
# Re-run \`make install-shell-env\` to refresh. Safe to source from an
# interactive shell rc; contains NO secret values.
#
# Why: vornikctl performs the same config load + validation as the daemon but
# resolves paths and secrets from YOUR SHELL, not from the systemd unit. Without
# this, commands like \`vornikctl backup\` fail on unrelated validation rules
# (e.g. web.submit_secret) simply because the shell lacks the daemon's env.
#
# Non-secret paths. Taken from the running systemd unit when one existed at
# generation time, else from the install defaults. If you later change the unit,
# regenerate this file — it does NOT track the unit at runtime.
export VORNIK_CONFIG="${resolved_config}"
export VORNIK_CONFIGS_DIR="${resolved_configs_dir}"
export VORNIK_DATA_DIR="${resolved_data}"

# Deny this deployment's own database as a memory-benchmark target.
#
# The benchmark bulk-writes and CLEARS its target. Its guard denies the generic
# names (prod / production / live) and asks the daemon which database it actually
# writes — but a name that agrees with the daemon is allowed, so a production
# database whose name reads like a scratch one is not protected by either check.
# This deployment's does. Naming it here is what denies it at all.
#
# The variable may only ADD denials, so inheriting it into child processes cannot
# weaken anything: the worst case of forgetting it is a denial that does not
# happen, never a protection silently removed.
${resolved_db:+export VORNIK_BENCH_DENY_DATABASES="${resolved_db}"}

# Secrets: sourced from the 0600 files the unit's own EnvironmentFile= lines
# use, so there is exactly ONE copy of each secret on disk. Never inline a
# secret value into a shell rc — those are typically world-readable (0644).
#
# Note this exports the secrets into every shell that sources it, and thus into
# child processes. That is the intended trade for a single-operator admin host;
# on a shared machine, prefer sourcing on demand instead of from your rc.
#
# \`set -a\` makes the plain KEY=value lines exported. The files are trusted
# operator-authored input at the same trust level as your shell rc.
for _vornik_env in "${secrets_dir}"/env "${secrets_dir}"/*.env; do
  [ -r "\$_vornik_env" ] || continue
  set -a
  # shellcheck disable=SC1090 # runtime path, intentionally dynamic
  . "\$_vornik_env"
  set +a
done
unset _vornik_env
EOF
chmod 0644 "$OUT"
echo "wrote $OUT"
