package projectdeps

import (
	"errors"
	"strings"
	"testing"
)

const goodLock = `# generated by pip-compile --generate-hashes
--index-url https://pypi.org/simple

numpy==1.26.4 \
    --hash=sha256:aaaa \
    --hash=sha256:bbbb
soundfile==0.12.1 --hash=sha256:cccc
`

func TestRequireHashPinnedAcceptsAGeneratedLockfile(t *testing.T) {
	if err := RequireHashPinned("requirements.lock", []byte(goodLock)); err != nil {
		t.Fatalf("RequireHashPinned() = %v, want nil", err)
	}
}

func TestRequireHashPinnedRefusals(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		wantLine int
		wantErr  string
	}{
		{
			// The whole point of the key: a pinned version with no hash
			// still resolves to different wheels over time (re-uploads,
			// yanks), so the key could not support its own claim.
			name:     "pinned but hashless",
			content:  "numpy==1.26.4\n",
			wantLine: 1,
			wantErr:  "carries no --hash=",
		},
		{
			name:     "hashed but floating",
			content:  "numpy>=1.26 --hash=sha256:aaaa\n",
			wantLine: 1,
			wantErr:  "not pinned with ==",
		},
		{
			// The key is computed over THIS file's bytes; an include
			// puts part of the resolution outside it, so a cache hit
			// would reuse a materialisation whose include has changed.
			name:     "-r include",
			content:  "numpy==1.0 --hash=sha256:a\n-r other.txt\n",
			wantLine: 2,
			wantErr:  "outside this file",
		},
		{
			name:     "-c constraint include",
			content:  "-c constraints.txt\n",
			wantLine: 1,
			wantErr:  "outside this file",
		},
		{
			name:     "editable install",
			content:  "-e .\n",
			wantLine: 1,
			wantErr:  "cannot be content-addressed",
		},
		{
			// An empty tree would mount and report healthy while every
			// import still failed.
			name:    "options only",
			content: "--index-url https://pypi.org/simple\n",
			wantErr: "declares no requirements",
		},
		{
			name:    "comments and blanks only",
			content: "# nothing here\n\n   \n",
			wantErr: "declares no requirements",
		},
		{
			name:     "the hashless line is found after good ones",
			content:  goodLock + "pyyaml==6.0\n",
			wantLine: 8,
			wantErr:  "carries no --hash=",
		},
		{
			name:     "a continuation without a hash reports its FIRST line",
			content:  "numpy==1.0 \\\n    --no-binary :all:\n",
			wantLine: 1,
			wantErr:  "carries no --hash=",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := RequireHashPinned("requirements.lock", []byte(tt.content))
			if err == nil {
				t.Fatalf("RequireHashPinned() = nil, want error containing %q", tt.wantErr)
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Fatalf("RequireHashPinned() = %q, want it to contain %q", err, tt.wantErr)
			}
			var le LockfileError
			if !errors.As(err, &le) {
				t.Fatalf("got %T, want LockfileError so the operator is sent to a line", err)
			}
			if tt.wantLine != 0 && le.Line != tt.wantLine {
				t.Fatalf("line = %d, want %d (%q)", le.Line, tt.wantLine, err)
			}
		})
	}
}

func TestRequireHashPinnedIgnoresTrailingComments(t *testing.T) {
	// pip-compile annotates every pin with a "# via …" comment.
	content := "numpy==1.26.4 --hash=sha256:aaaa  # via -r requirements.in\n"
	if err := RequireHashPinned("requirements.lock", []byte(content)); err != nil {
		t.Fatalf("an annotation comment must not read as an include: %v", err)
	}
}

func TestLockfileErrorMessage(t *testing.T) {
	if got := (LockfileError{Path: "r.lock", Line: 4, Message: "boom"}).Error(); got != "r.lock:4: boom" {
		t.Fatalf("Error() = %q", got)
	}
	if got := (LockfileError{Path: "r.lock", Message: "boom"}).Error(); got != "r.lock: boom" {
		t.Fatalf("Error() = %q", got)
	}
}

func TestRequireHashPinnedSurfacesAReadError(t *testing.T) {
	// A lockfile with a line past the scanner's ceiling must refuse, not
	// silently validate the lines it managed to read.
	huge := "numpy==1.0 " + strings.Repeat("a", 2*1024*1024) + "\n"
	err := RequireHashPinned("requirements.lock", []byte(huge))
	if err == nil || !strings.Contains(err.Error(), "could not be read") {
		t.Fatalf("RequireHashPinned() = %v, want a read failure", err)
	}
}
